server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  config:
    import: secrets.yml
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  h2:
    console:
      enabled: true