budget-guard:
  api-key:
    key: X-API-KEY
    value: cbf94cc5-98f9-4da4-bc6f-67b0bc16e129

server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  h2:
    console:
      enabled: true